export const SET_BOOK = "[APP] SET_BOOK"
export const SET_CHAPTER = "[APP] SET_CHAPTER"
export const SET_FONT_SIZE = "[APP] SET_FONT_SIZE"
export const SET_MODAL_VISIBLE = "[APP] SET_MODAL_VISIBLE"

export const CURRENT_BOOK_FETCH = "[CURRENT] CURRENT_BOOK_FETCH"
export const CURRENT_BOOK_SUCCESS = "[CURRENT] CURRENT_BOOK_SUCCESS"
export const CURRENT_BOOK_ERROR = "[CURRENT] CURRENT_BOOK_ERROR"

export const BOOK_LIST_FETCH = "[BOOK] BOOK_LIST_FETCH"
export const BOOK_LIST_SUCCESS = "[BOOK] BOOK_LIST_SUCCESS"
export const BOOK_LIST_ERROR = "[BOOK] BOOK_LIST_ERROR"

export const VERSE_LIST_FETCH = "[VERSE] VERSE_LIST_FETCH"
export const VERSE_LIST_SUCCESS = "[VERSE] VERSE_LIST_SUCCESS"
export const VERSE_LIST_ERROR = "[VERSE] VERSE_LIST_ERROR"

export const CHAPTER_LIST_FETCH = "[CHAPTER] CHAPTER_LIST_FETCH"
export const CHAPTER_LIST_SUCCESS = "[CHAPTER] CHAPTER_LIST_SUCCESS"
export const CHAPTER_LIST_ERROR = "[CHAPTER] CHAPTER_LIST_ERROR"
