export const SET_BOOK = "[APP] SET_BOOK"
export const SET_CHAPTER = "[APP] SET_CHAPTER"
export const SET_VERSION = "[APP] SET_VERSION"
export const SET_THEME = "[APP] SET_THEME"
export const SET_FONT_SIZE = "[APP] SET_FONT_SIZE"
export const SET_MODAL_VISIBLE = "[APP] SET_MODAL_VISIBLE"

export const CURRENT_BOOK_FETCH = "[CURRENT] CURRENT_BOOK_FETCH"
export const CURRENT_BOOK_SUCCESS = "[CURRENT] CURRENT_BOOK_SUCCESS"
export const CURRENT_BOOK_ERROR = "[CURRENT] CURRENT_BOOK_ERROR"

export const BOOK_LIST_FETCH = "[BOOK] BOOK_LIST_FETCH"
export const BOOK_LIST_SUCCESS = "[BOOK] BOOK_LIST_SUCCESS"
export const BOOK_LIST_ERROR = "[BOOK] BOOK_LIST_ERROR"

export const VERSE_LIST_FETCH = "[VERSE] VERSE_LIST_FETCH"
export const VERSE_LIST_SUCCESS = "[VERSE] VERSE_LIST_SUCCESS"
export const VERSE_LIST_ERROR = "[VERSE] VERSE_LIST_ERROR"

export const CHAPTER_LIST_FETCH = "[CHAPTER] CHAPTER_LIST_FETCH"
export const CHAPTER_LIST_SUCCESS = "[CHAPTER] CHAPTER_LIST_SUCCESS"
export const CHAPTER_LIST_ERROR = "[CHAPTER] CHAPTER_LIST_ERROR"

export const CONFIG_SAVE_FETCH = "[CONFIG] CONFIG_SAVE_FETCH"
export const CONFIG_SAVE_SUCCESS = "[CONFIG] CONFIG_SAVE_SUCCESS"
export const CONFIG_SAVE_ERROR = "[CONFIG] CONFIG_SAVE_ERROR"

export const CONFIG_MOVE_FETCH = "[CONFIG] CONFIG_MOVE_FETCH"
export const CONFIG_MOVE_SUCCESS = "[CONFIG] CONFIG_MOVE_SUCCESS"
export const CONFIG_MOVE_ERROR = "[CONFIG] CONFIG_MOVE_ERROR"

export const CONFIG_LIST_FETCH = "[CONFIG] CONFIG_LIST_FETCH"
export const CONFIG_LIST_SUCCESS = "[CONFIG] CONFIG_LIST_SUCCESS"
export const CONFIG_LIST_ERROR = "[CONFIG] CONFIG_LIST_ERROR"

export const MARK_SAVE_FETCH = "[CONFIG] MARK_SAVE_FETCH"
export const MARK_SAVE_SUCCESS = "[CONFIG] MARK_SAVE_SUCCESS"
export const MARK_SAVE_ERROR = "[CONFIG] MARK_SAVE_ERROR"

export const GET_MARK_FETCH = "[CONFIG] GET_MARK_FETCH"
export const GET_MARK_SUCCESS = "[CONFIG] GET_MARK_SUCCESS"
export const GET_MARK_ERROR = "[CONFIG] GET_MARK_ERROR"

export const REMOVE_MARK_FETCH = "[CONFIG] REMOVE_MARK_FETCH"
export const REMOVE_MARK_SUCCESS = "[CONFIG] REMOVE_MARK_SUCCESS"
export const REMOVE_MARK_ERROR = "[CONFIG] REMOVE_MARK_ERROR"
